centerBody:
  r: [0, 0, 0]
  v: [0, 0, 0]
  mass: 5.972 * 10 ** 24 # kg
  radius: 6,371 # km
fullRightBody:
  r: [0, 0, 0]
  v: [0, 0, 0]
  mass: 5.972 * 10 ** 24 # kg
  radius: 6,371 # km
upperRightBody:
  r: [0, 0, 0]
  v: [0, 0, 0]
  mass: 5.972 * 10 ** 24 # kg
  radius: 6,371 # km
lowerRightBody:
  r: [0, 0, 0]
  v: [0, 0, 0]
  mass: 5.972 * 10 ** 24 # kg
  radius: 6,371 # km
leftLowerRightBody:
  r: [0, 0, 0]
  v: [0, 0, 0]
  mass: 5.972 * 10 ** 24 # kg
  radius: 6,371 # km
rightLowerRightBody:
  r: [0, 0, 0]
  v: [0, 0, 0]
  mass: 5.972 * 10 ** 24 # kg
  radius: 6,371 # km
leftUpperRightBody:
  r: [0, 0, 0]
  v: [0, 0, 0]
  mass: 5.972 * 10 ** 24 # kg
  radius: 6,371 # km
rightUpperRightBody:
  r: [0, 0, 0]
  v: [0, 0, 0]
  mass: 5.972 * 10 ** 24 # kg
  radius: 6,371 # km
