body1:
  r: [0, 0, 0] # km
  v: [0, 0, 0] # m/s
  mass: 5.972 * 10 ** 24 # kg
  radius: 6371 # km
body2:
  r: [12742, 12742, 0] # km
  v: [0, 0, 0] # m/s
  mass: 5.972 * 10 ** 24 # kg
  radius: 6371 # km
body3:
  r: [-12742, -12742, 0] # km
  v: [0, 0, 0] # m/s
  mass: 5.972 * 10 ** 24 # kg
  radius: 6371 # km